<?php

namespace App\Services;

use App\Services\ThunderbirdService;
use App\Services\EmailClassificationService;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Cache;
use Exception;

/**
 * Unified Email Service (EA2)
 *
 * Provides comprehensive email functionality for the PLOS framework:
 * - Full email client access (read, search, send)
 * - AI-powered classification and categorization
 * - Draft queue with human approval workflow
 * - Configurable folder monitoring
 *
 * Architecture:
 * EmailService
 *   ├── ThunderbirdService (MCP communication)
 *   └── EmailClassificationService (AI features)
 *
 * Draft Sources:
 * - ai_reply: AI-generated reply suggestions
 * - workflow: Emails generated by workflow nodes
 * - data_removal: Data broker removal emails
 * - manual: (future) Manual composition via UI
 */
class EmailService
{
    private ThunderbirdService $thunderbird;
    private EmailClassificationService $classifier;
    private ?EmailRateLimitService $rateLimitService = null;

    // Error tracking
    private array $errors = [];
    private int $operationCount = 0;

    // Settings cache key
    private const SETTINGS_CACHE_KEY = 'email_service_settings';
    /** @see config/timeouts.php cache.email */

    public function __construct(
        ThunderbirdService $thunderbird,
        EmailClassificationService $classifier,
        ?EmailRateLimitService $rateLimitService = null
    ) {
        $this->thunderbird = $thunderbird;
        $this->classifier = $classifier;
        $this->rateLimitService = $rateLimitService;
    }

    // =========================================================================
    // CONNECTION & STATUS
    // =========================================================================

    /**
     * Check if email service is available
     */
    public function isAvailable(): bool
    {
        return $this->thunderbird->isAvailable();
    }

    /**
     * Get comprehensive service status
     */
    public function getStatus(): array
    {
        $thunderbirdStatus = $this->thunderbird->getConnectionStatus();

        $status = [
            'available' => $thunderbirdStatus['available'],
            'thunderbird' => $thunderbirdStatus,
            'classification' => $this->getClassificationStatus(),
            'draft_queue' => $this->getDraftQueueStats(),
            'settings' => $this->getSettings(),
            'errors' => $this->errors,
            'operation_count' => $this->operationCount,
        ];

        return $status;
    }

    /**
     * Get email statistics
     */
    public function getStats(): array
    {
        $stats = [
            'thunderbird' => null,
            'classification' => null,
            'drafts' => null,
        ];

        try {
            if ($this->thunderbird->isAvailable()) {
                $stats['thunderbird'] = $this->thunderbird->getStats();
            }
        } catch (Exception $e) {
            $this->recordError('stats_thunderbird', $e->getMessage());
        }

        try {
            $stats['classification'] = $this->classifier->getStats();
        } catch (Exception $e) {
            $this->recordError('stats_classification', $e->getMessage());
        }

        $stats['drafts'] = $this->getDraftQueueStats();

        return $stats;
    }

    // =========================================================================
    // EMAIL READING
    // =========================================================================

    /**
     * List all available email folders
     */
    public function listFolders(): array
    {
        $this->operationCount++;

        try {
            return $this->thunderbird->listFolders();
        } catch (Exception $e) {
            $this->recordError('list_folders', $e->getMessage());
            throw $e;
        }
    }

    /**
     * List configured mailboxes/accounts
     */
    public function listMailboxes(): array
    {
        $this->operationCount++;

        try {
            return $this->thunderbird->listMailboxes();
        } catch (Exception $e) {
            $this->recordError('list_mailboxes', $e->getMessage());
            throw $e;
        }
    }

    /**
     * Search emails across folders
     *
     * @param string $query Search query
     * @param string|null $folder Optional folder filter
     * @return array Matching emails
     */
    public function searchEmails(string $query, ?string $folder = null): array
    {
        $this->operationCount++;

        if (empty(trim($query))) {
            throw new Exception('Search query cannot be empty');
        }

        try {
            return $this->thunderbird->searchMessages($query, $folder);
        } catch (Exception $e) {
            $this->recordError('search_emails', $e->getMessage());
            throw $e;
        }
    }

    /**
     * Get recent emails from a folder
     *
     * @param string $folder Folder name (default: Inbox)
     * @param int $limit Number of emails (default: 10)
     * @return array Recent emails
     */
    public function getRecentEmails(string $folder = 'Inbox', int $limit = 10): array
    {
        $this->operationCount++;

        try {
            return $this->thunderbird->getRecentMessages($folder, $limit);
        } catch (Exception $e) {
            $this->recordError('get_recent', $e->getMessage());
            throw $e;
        }
    }

    // =========================================================================
    // EMAIL SENDING
    // =========================================================================

    /**
     * Send email immediately via Thunderbird
     *
     * @param string $to Recipient email
     * @param string $subject Email subject
     * @param string $body Email body
     * @param string|null $from Sender mailbox (optional, uses default)
     * @return array Send result
     */
    public function sendEmail(string $to, string $subject, string $body, ?string $from = null): array
    {
        $this->operationCount++;

        $params = [
            'to' => $to,
            'subject' => $subject,
            'body' => $body,
        ];

        if ($from) {
            $params['mailbox'] = $from;
        }

        try {
            $result = $this->thunderbird->sendEmail($params);

            // Log successful send
            Log::info('EmailService: Email sent', [
                'to' => $to,
                'subject' => $subject,
                'result' => $result,
            ]);

            return [
                'success' => true,
                'result' => $result,
            ];

        } catch (Exception $e) {
            $this->recordError('send_email', $e->getMessage());

            Log::error('EmailService: Send failed', [
                'to' => $to,
                'subject' => $subject,
                'error' => $e->getMessage(),
            ]);

            return [
                'success' => false,
                'error' => $e->getMessage(),
            ];
        }
    }

    /**
     * Send email with bounce check
     *
     * Checks suppression list before sending. If email is suppressed,
     * returns error without attempting to send.
     *
    /**
     * Send email with full pre-send checks (bounce + rate limiting)
     *
     * This is the recommended method for sending emails as it performs:
     * - Suppression list check (bounces/complaints)
     * - Rate limit check (daily/hourly limits)
     * - Domain throttling (delays for problematic domains)
     * - Cooldown verification
     *
     * @param string $to Recipient email
     * @param string $subject Email subject
     * @param string $body Email body
     * @param string|null $from Sender mailbox (optional, uses default)
     * @return array Result with success status and details
     */
    public function sendEmailWithAllChecks(string $to, string $subject, string $body, ?string $from = null): array
    {
        $this->operationCount++;

        // Determine sender mailbox
        $mailbox = $from ?? $this->getDefaultMailbox();
        if (!$mailbox) {
            return [
                'success' => false,
                'error' => 'No sender mailbox specified and no default configured',
            ];
        }

        // Extract recipient domain
        $recipientDomain = $this->extractDomain($to);

        // Check rate limits
        if ($this->rateLimitService && !$this->rateLimitService->canSend($mailbox, $recipientDomain)) {
            $quota = $this->rateLimitService->getRemainingQuota($mailbox);

            Log::warning('EmailService: Rate limit blocked send', [
                'mailbox' => $mailbox,
                'to' => $to,
                'quota' => $quota,
            ]);

            return [
                'success' => false,
                'error' => $quota['in_cooldown']
                    ? 'Mailbox is in cooldown period'
                    : 'Rate limit exceeded (daily: ' . $quota['daily_remaining'] . ' remaining, hourly: ' . $quota['hourly_remaining'] . ' remaining)',
                'suppressed' => false,
                'rate_limited' => true,
                'quota' => $quota,
            ];
        }

        // Apply domain-specific delay if needed
        if ($this->rateLimitService) {
            $delay = $this->rateLimitService->getDomainDelay($recipientDomain);
            if ($delay > 0) {
                usleep($delay * 1000); // Convert ms to microseconds
            }
        }

        // Send the email
        $result = $this->sendEmail($to, $subject, $body, $from);

        // Record the send if successful
        if ($result['success'] && $this->rateLimitService) {
            $this->rateLimitService->recordSend($mailbox, $recipientDomain);
        }

        return array_merge($result, [
            'suppressed' => false,
            'rate_limited' => false,
        ]);
    }

    /**
     * Get rate limit service for direct access
     */
    public function getRateLimitService(): ?EmailRateLimitService
    {
        return $this->rateLimitService;
    }

    /**
     * Get remaining email quota for a mailbox
     *
     * @param string|null $mailbox Mailbox to check (null = default)
     * @return array|null Quota info or null if rate limiting not configured
     */
    public function getEmailQuota(?string $mailbox = null): ?array
    {
        if (!$this->rateLimitService) {
            return null;
        }

        $mailbox = $mailbox ?? $this->getDefaultMailbox();
        if (!$mailbox) {
            return null;
        }

        return $this->rateLimitService->getRemainingQuota($mailbox);
    }

    /**
     * Extract domain from email address
     */
    private function extractDomain(string $email): string
    {
        $parts = explode('@', strtolower(trim($email)));
        return $parts[1] ?? 'unknown';
    }

    /**
     * Get default mailbox from settings
     */
    private function getDefaultMailbox(): ?string
    {
        $settings = $this->getSettings();
        return $settings['default_mailbox'] ?? config('mail.from.address');
    }

    // =========================================================================
    // DRAFT QUEUE MANAGEMENT
    // =========================================================================

    /**
     * Queue an email draft for human approval
     *
     * @param array $email Email data (to, subject, body, etc.)
     * @param string $source Source identifier (ai_reply, workflow, data_removal)
     * @param array $options Additional options (priority, related_type, related_id)
     * @return int Draft ID
     */
    public function queueDraft(array $email, string $source = 'workflow', array $options = []): int
    {
        $this->operationCount++;

        // Validate required fields
        $required = ['to', 'subject', 'body'];
        foreach ($required as $field) {
            if (empty($email[$field])) {
                throw new Exception("Missing required field for draft: {$field}");
            }
        }

        // Validate email format
        if (!filter_var($email['to'], FILTER_VALIDATE_EMAIL)) {
            throw new Exception("Invalid email address: {$email['to']}");
        }

        $sql = "INSERT INTO email_reply_drafts
                (original_message_id, source, `to`, from_address, cc, bcc, subject, body,
                 ai_suggestions, status, priority, template_id, workflow_execution_id,
                 related_type, related_id, metadata, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try {
            DB::insert($sql, [
                $email['original_message_id'] ?? null,
                $source,
                $email['to'],
                $email['from'] ?? null,
                $email['cc'] ?? null,
                $email['bcc'] ?? null,
                $email['subject'],
                $email['body'],
                $email['ai_suggestions'] ?? null,
                'draft',
                $options['priority'] ?? 'normal',
                $options['template_id'] ?? null,
                $options['workflow_execution_id'] ?? null,
                $options['related_type'] ?? null,
                $options['related_id'] ?? null,
                json_encode($email['metadata'] ?? []),
                now(),
                now(),
            ]);

            $draftId = (int) DB::getPdo()->lastInsertId();

            // Record draft version
            try {
                app(\App\Services\EmailEnhancementsService::class)
                    ->saveDraftVersion($draftId, $email['body'], 'ai', 'created');
            } catch (\Exception $e) {
                Log::warning('EmailService: Failed to save draft version', ['error' => $e->getMessage()]);
            }

            Log::info('EmailService: Draft queued', [
                'draft_id' => $draftId,
                'source' => $source,
                'to' => $email['to'],
                'subject' => $email['subject'],
            ]);

            return $draftId;

        } catch (Exception $e) {
            $this->recordError('queue_draft', $e->getMessage());
            throw $e;
        }
    }

    /**
     * Get pending drafts from queue
     *
     * @param array $filters Optional filters (source, priority, limit)
     * @return array Pending drafts
     */
    public function getPendingDrafts(array $filters = []): array
    {
        $sql = "SELECT * FROM email_reply_drafts WHERE status = 'pending'";
        $params = [];

        if (!empty($filters['source'])) {
            $sql .= " AND source = ?";
            $params[] = $filters['source'];
        }

        if (!empty($filters['priority'])) {
            $sql .= " AND priority = ?";
            $params[] = $filters['priority'];
        }

        $sql .= " ORDER BY
            CASE priority
                WHEN 'urgent' THEN 1
                WHEN 'high' THEN 2
                WHEN 'normal' THEN 3
                WHEN 'low' THEN 4
            END,
            created_at ASC";

        $limit = $filters['limit'] ?? 50;
        $sql .= " LIMIT " . (int) $limit;

        return DB::select($sql, $params);
    }

    /**
     * Get a specific draft by ID
     *
     * @param int $draftId Draft ID
     * @return object|null Draft record or null
     */
    public function getDraft(int $draftId): ?object
    {
        $result = DB::selectOne(
            "SELECT * FROM email_reply_drafts WHERE id = ?",
            [$draftId]
        );

        return $result ?: null;
    }

    /**
     * Update a draft
     *
     * @param int $draftId Draft ID
     * @param array $updates Fields to update
     * @return bool Success
     */
    public function updateDraft(int $draftId, array $updates): bool
    {
        $allowedFields = ['to', 'from_address', 'cc', 'bcc', 'subject', 'body', 'priority'];
        $setClauses = [];
        $params = [];

        foreach ($updates as $field => $value) {
            if (in_array($field, $allowedFields)) {
                $setClauses[] = "`{$field}` = ?";
                $params[] = $value;
            }
        }

        if (empty($setClauses)) {
            return false;
        }

        $setClauses[] = "updated_at = ?";
        $params[] = now();
        $params[] = $draftId;

        $sql = "UPDATE email_reply_drafts SET " . implode(', ', $setClauses) . " WHERE id = ?";

        $updated = DB::update($sql, $params) > 0;

        // Record draft version on edit
        if ($updated && isset($updates['body'])) {
            try {
                app(\App\Services\EmailEnhancementsService::class)
                    ->saveDraftVersion($draftId, $updates['body'], 'human', 'edited');
            } catch (\Exception $e) {
                Log::warning('EmailService: Failed to save draft version', ['error' => $e->getMessage()]);
            }
        }

        return $updated;
    }

    /**
     * Approve and send a draft
     *
     * @param int $draftId Draft ID
     * @return array Result with success status
     */
    public function approveDraft(int $draftId): array
    {
        $this->operationCount++;

        $draft = $this->getDraft($draftId);

        if (!$draft) {
            return [
                'success' => false,
                'error' => "Draft not found: {$draftId}",
            ];
        }

        if ($draft->status !== 'pending') {
            return [
                'success' => false,
                'error' => "Draft already processed (status: {$draft->status})",
            ];
        }

        // Attempt to send (with full suppression + rate limit checks)
        $sendResult = $this->sendEmailWithAllChecks(
            $draft->to,
            $draft->subject,
            $draft->body,
            $draft->from_address
        );

        if ($sendResult['success']) {
            // Update draft status
            DB::update(
                "UPDATE email_reply_drafts
                 SET status = 'sent', approved_at = ?, sent_at = ?, updated_at = ?
                 WHERE id = ?",
                [now(), now(), now(), $draftId]
            );

            // Record approved version
            try {
                app(\App\Services\EmailEnhancementsService::class)
                    ->saveDraftVersion($draftId, $draft->body, 'human', 'approved');
            } catch (\Exception $e) {
                Log::warning('EmailService: Failed to save draft version', ['error' => $e->getMessage()]);
            }

            Log::info('EmailService: Draft approved and sent', [
                'draft_id' => $draftId,
                'to' => $draft->to,
            ]);

            return [
                'success' => true,
                'draft_id' => $draftId,
                'send_result' => $sendResult['result'],
            ];

        } else {
            // Mark as failed
            DB::update(
                "UPDATE email_reply_drafts
                 SET status = 'failed', metadata = JSON_SET(COALESCE(metadata, '{}'), '$.send_error', ?), updated_at = ?
                 WHERE id = ?",
                [$sendResult['error'], now(), $draftId]
            );

            return [
                'success' => false,
                'error' => $sendResult['error'],
                'draft_id' => $draftId,
            ];
        }
    }

    /**
     * Reject a draft
     *
     * @param int $draftId Draft ID
     * @param string|null $reason Optional rejection reason
     * @return bool Success
     */
    public function rejectDraft(int $draftId, ?string $reason = null): bool
    {
        $this->operationCount++;

        $metadata = $reason ? json_encode(['rejection_reason' => $reason]) : null;

        $updated = DB::update(
            "UPDATE email_reply_drafts
             SET status = 'rejected', metadata = COALESCE(?, metadata), updated_at = ?
             WHERE id = ? AND status = 'pending'",
            [$metadata, now(), $draftId]
        );

        if ($updated) {
            // Record rejected version
            try {
                app(\App\Services\EmailEnhancementsService::class)
                    ->saveDraftVersion($draftId, '', 'human', 'rejected');
            } catch (\Exception $e) {
                Log::warning('EmailService: Failed to save draft version', ['error' => $e->getMessage()]);
            }

            Log::info('EmailService: Draft rejected', [
                'draft_id' => $draftId,
                'reason' => $reason,
            ]);
        }

        return $updated > 0;
    }

    /**
     * Get draft queue statistics
     */
    public function getDraftQueueStats(): array
    {
        $stats = DB::select("
            SELECT
                status,
                source,
                COUNT(*) as count
            FROM email_reply_drafts
            GROUP BY status, source
        ");

        $byStatus = [];
        $bySource = [];

        foreach ($stats as $row) {
            $byStatus[$row->status] = ($byStatus[$row->status] ?? 0) + $row->count;
            $bySource[$row->source] = ($bySource[$row->source] ?? 0) + $row->count;
        }

        $pendingCount = $byStatus['pending'] ?? 0;
        $urgentCount = DB::selectOne(
            "SELECT COUNT(*) as count FROM email_reply_drafts WHERE status = 'pending' AND priority = 'urgent'"
        )->count ?? 0;

        return [
            'pending' => $pendingCount,
            'urgent' => $urgentCount,
            'by_status' => $byStatus,
            'by_source' => $bySource,
            'total' => array_sum($byStatus),
        ];
    }

    // =========================================================================
    // AI CLASSIFICATION
    // =========================================================================

    /**
     * Classify an email using AI
     *
     * @param array $email Email data
     * @return array Classification result
     */
    public function classifyEmail(array $email): array
    {
        $this->operationCount++;

        try {
            return $this->classifier->classifyEmail($email);
        } catch (Exception $e) {
            $this->recordError('classify', $e->getMessage());
            throw $e;
        }
    }

    /**
     * Classify recent emails from a folder
     *
     * @param string $folder Folder name
     * @param int $limit Number to classify
     * @return array Classification results
     */
    public function classifyRecentEmails(string $folder = 'Inbox', int $limit = 10): array
    {
        $this->operationCount++;

        try {
            $emails = $this->getRecentEmails($folder, $limit);
            $results = [];

            foreach ($emails as $email) {
                try {
                    $result = $this->classifier->classifyEmail($email);
                    $results[] = [
                        'email' => $email,
                        'classification' => $result['classification'],
                        'success' => $result['success'],
                    ];
                } catch (Exception $e) {
                    $results[] = [
                        'email' => $email,
                        'error' => $e->getMessage(),
                        'success' => false,
                    ];
                }
            }

            return [
                'total' => count($emails),
                'classified' => count(array_filter($results, fn($r) => $r['success'])),
                'results' => $results,
            ];

        } catch (Exception $e) {
            $this->recordError('classify_recent', $e->getMessage());
            throw $e;
        }
    }

    /**
     * Generate AI reply for an email
     *
     * @param string $messageId Original message ID
     * @param array $email Email data
     * @param array $options Generation options (template_id, tone)
     * @return int Draft ID
     */
    public function generateReplyDraft(string $messageId, array $email, array $options = []): int
    {
        $this->operationCount++;

        try {
            return $this->classifier->generateReplyDraft($messageId, $email, $options);
        } catch (Exception $e) {
            $this->recordError('generate_reply', $e->getMessage());
            throw $e;
        }
    }

    /**
     * Get classification statistics
     */
    public function getClassificationStats(): array
    {
        return $this->classifier->getStats();
    }

    // =========================================================================
    // CONFIGURATION
    // =========================================================================

    /**
     * Get email service settings
     */
    public function getSettings(): array
    {
        return Cache::remember(self::SETTINGS_CACHE_KEY, config('timeouts.cache.email', 3600), function () {
            $settings = DB::select("SELECT setting_key, setting_value FROM email_settings");

            $result = [
                'monitored_folders' => ['Inbox'],
                'default_mailbox' => null,
                'auto_classify' => true,
                'classification_batch_size' => 10,
            ];

            foreach ($settings as $row) {
                $value = $row->setting_value;

                // Try to decode JSON values
                if ($value !== null) {
                    $decoded = json_decode($value, true);
                    $result[$row->setting_key] = (json_last_error() === JSON_ERROR_NONE) ? $decoded : $value;
                } else {
                    $result[$row->setting_key] = null;
                }
            }

            return $result;
        });
    }

    /**
     * Get monitored folders
     */
    public function getMonitoredFolders(): array
    {
        $settings = $this->getSettings();
        return $settings['monitored_folders'] ?? ['Inbox'];
    }

    /**
     * Update monitored folders
     *
     * @param array $folders List of folder names to monitor
     */
    public function setMonitoredFolders(array $folders): void
    {
        $this->saveSetting('monitored_folders', $folders);
    }

    /**
     * Update a setting
     *
     * @param string $key Setting key
     * @param mixed $value Setting value
     */
    public function saveSetting(string $key, $value): void
    {
        $jsonValue = is_array($value) ? json_encode($value) : (string) $value;

        // Upsert setting
        $exists = DB::selectOne(
            "SELECT id FROM email_settings WHERE setting_key = ?",
            [$key]
        );

        if ($exists) {
            DB::update(
                "UPDATE email_settings SET setting_value = ?, updated_at = ? WHERE setting_key = ?",
                [$jsonValue, now(), $key]
            );
        } else {
            DB::insert(
                "INSERT INTO email_settings (setting_key, setting_value, created_at, updated_at) VALUES (?, ?, ?, ?)",
                [$key, $jsonValue, now(), now()]
            );
        }

        // Clear cache
        Cache::forget(self::SETTINGS_CACHE_KEY);

        Log::info('EmailService: Setting updated', [
            'key' => $key,
            'value' => $value,
        ]);
    }

    // =========================================================================
    // DIAGNOSTICS
    // =========================================================================

    /**
     * Get classification service status
     */
    private function getClassificationStatus(): array
    {
        try {
            $stats = $this->classifier->getStats();
            return [
                'available' => true,
                'total_classified' => $stats['total_classified'] ?? 0,
            ];
        } catch (Exception $e) {
            return [
                'available' => false,
                'error' => $e->getMessage(),
            ];
        }
    }

    /**
     * Record an error for diagnostics
     */
    private function recordError(string $operation, string $message): void
    {
        $this->errors[] = [
            'operation' => $operation,
            'message' => $message,
            'timestamp' => now()->toIso8601String(),
        ];

        // Keep only last 10 errors
        if (count($this->errors) > 10) {
            array_shift($this->errors);
        }
    }

    /**
     * Get recorded errors
     */
    public function getErrors(): array
    {
        return $this->errors;
    }

    /**
     * Reset circuit breaker on Thunderbird service
     */
    public function resetThunderbirdCircuit(): void
    {
        $this->thunderbird->resetCircuit();
    }
}
