<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * FC-8: Expand verdict constraint from 3-class to 5-class (PolitiFact/FACT5 standard)
 *
 * Old: supported, refuted, inconclusive
 * New: true, mostly_true, half_true, mostly_false, false, inconclusive
 *
 * Also keeps legacy values (supported, refuted) for backwards compatibility
 * with existing data — they won't be generated by new code but existing
 * rows shouldn't break the constraint.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::connection('pgsql_rag')->statement("
            ALTER TABLE verdicts DROP CONSTRAINT IF EXISTS chk_verdict
        ");

        DB::connection('pgsql_rag')->statement("
            ALTER TABLE verdicts ADD CONSTRAINT chk_verdict
            CHECK (verdict IN ('true', 'mostly_true', 'half_true', 'mostly_false', 'false',
                               'inconclusive', 'supported', 'refuted'))
        ");
    }

    public function down(): void
    {
        DB::connection('pgsql_rag')->statement("
            ALTER TABLE verdicts DROP CONSTRAINT IF EXISTS chk_verdict
        ");

        DB::connection('pgsql_rag')->statement("
            ALTER TABLE verdicts ADD CONSTRAINT chk_verdict
            CHECK (verdict IN ('supported', 'refuted', 'inconclusive'))
        ");
    }
};
