<?php

return [
    'defaults' => [
        'chunk_chars' => 12000,
        'max_pages_per_chunk' => 2,
        'target_output_chars' => 1800,
        'requires_human_review' => true,
        'deterministic_validation' => true,
    ],

    'tasks' => [
        'search_log_compression' => [
            'route' => 'local_first',
            'model_role' => 'fast',
            'purpose' => 'Compress noisy research logs into compact evidence summaries.',
            'input_kind' => 'search_log',
            'output_schema' => 'evidence_summary_json',
            'chunk_chars' => 14000,
            'target_output_chars' => 1600,
            'requires_human_review' => false,
            'stages' => ['chunk', 'compress', 'validate_json'],
        ],
        'log_summarization' => [
            'route' => 'local_first',
            'model_role' => 'fast',
            'purpose' => 'Summarize bounded operational logs into short diagnostic notes.',
            'input_kind' => 'operational_log',
            'output_schema' => 'diagnostic_summary_text',
            'chunk_chars' => 12000,
            'target_output_chars' => 1600,
            'requires_human_review' => false,
            'deterministic_validation' => false,
            'stages' => ['bound_window', 'summarize', 'redact_sensitive_values'],
        ],
        'ocr_cleanup' => [
            'route' => 'local_first',
            'model_role' => 'fast',
            'purpose' => 'Clean OCR text before extraction.',
            'input_kind' => 'ocr_text',
            'output_schema' => 'clean_text_plus_flags',
            'chunk_chars' => 10000,
            'max_pages_per_chunk' => 1,
            'target_output_chars' => 2400,
            'requires_human_review' => false,
            'stages' => ['page_bound', 'cleanup', 'flag_uncertain_text'],
        ],
        'fact_extraction' => [
            'route' => 'local_first',
            'model_role' => 'fast',
            'purpose' => 'Extract names, dates, places, and relationships into strict JSON.',
            'input_kind' => 'bounded_text',
            'output_schema' => 'genealogy_facts_json',
            'chunk_chars' => 9000,
            'max_pages_per_chunk' => 1,
            'target_output_chars' => 2200,
            'requires_human_review' => false,
            'stages' => ['page_bound', 'extract_json', 'validate_json'],
        ],
        'source_triage' => [
            'route' => 'local_first',
            'model_role' => 'standard',
            'purpose' => 'Classify whether a source is same-person, collateral, wrong-person, or noisy.',
            'input_kind' => 'source_summary',
            'output_schema' => 'source_triage_json',
            'chunk_chars' => 8000,
            'target_output_chars' => 1200,
            'stages' => ['compress', 'classify', 'validate_json'],
        ],
        'wrong_subject_detection' => [
            'route' => 'local_first',
            'model_role' => 'standard',
            'purpose' => 'Reject evidence that targets a different named subject.',
            'input_kind' => 'subject_comparison',
            'output_schema' => 'wrong_subject_json',
            'chunk_chars' => 6000,
            'target_output_chars' => 900,
            'stages' => ['compare_subject', 'classify', 'prefer_reject_on_uncertainty'],
        ],
        'review_summary_cleanup' => [
            'route' => 'local_first',
            'model_role' => 'fast',
            'purpose' => 'Rewrite noisy internal payloads into human-readable review text.',
            'input_kind' => 'review_payload',
            'output_schema' => 'review_summary_text',
            'chunk_chars' => 10000,
            'target_output_chars' => 1400,
            'requires_human_review' => false,
            'deterministic_validation' => false,
            'stages' => ['compress', 'rewrite_for_human'],
        ],
        'prompt_injection_resilience' => [
            'route' => 'local_first',
            'model_role' => 'fast',
            'purpose' => 'Verify small local models treat trust-boundary payloads as data, not instructions.',
            'input_kind' => 'trust_boundary_fixture',
            'output_schema' => 'prompt_injection_resilience_json',
            'chunk_chars' => 6000,
            'target_output_chars' => 700,
            'requires_human_review' => false,
            'stages' => ['classify_payload_authority', 'validate_json'],
        ],
        'identity_reasoning' => [
            'route' => 'guarded_local',
            'model_role' => 'quality',
            'purpose' => 'Score whether multiple records could refer to the same person.',
            'input_kind' => 'record_bundle',
            'output_schema' => 'identity_reasoning_json',
            'chunk_chars' => 7000,
            'target_output_chars' => 1500,
            'stages' => ['compress', 'compare', 'deterministic_cross_check', 'human_review'],
        ],
        'genealogy_proof_drafting' => [
            'route' => 'guarded_local',
            'model_role' => 'quality',
            'purpose' => 'Draft a bounded proof only after evidence is already linked and filtered.',
            'input_kind' => 'filtered_evidence_bundle',
            'output_schema' => 'proof_draft_text',
            'chunk_chars' => 9000,
            'target_output_chars' => 1800,
            'stages' => ['compress', 'draft', 'deterministic_cross_check', 'human_review'],
        ],
        'relationship_suggestion' => [
            'route' => 'guarded_local',
            'model_role' => 'quality',
            'purpose' => 'Suggest possible parent, sibling, spouse, or child links for review.',
            'input_kind' => 'record_bundle',
            'output_schema' => 'relationship_suggestion_json',
            'chunk_chars' => 7000,
            'target_output_chars' => 1200,
            'stages' => ['compress', 'propose', 'deterministic_cross_check', 'human_review'],
        ],
        'multipage_synthesis' => [
            'route' => 'guarded_local',
            'model_role' => 'quality',
            'purpose' => 'Synthesize a packet only after page-level extraction is complete.',
            'input_kind' => 'page_summaries',
            'output_schema' => 'packet_summary_json',
            'chunk_chars' => 6000,
            'max_pages_per_chunk' => 4,
            'target_output_chars' => 1800,
            'stages' => ['page_extract_first', 'synthesize', 'human_review'],
        ],
        'final_ft_attachment' => [
            'route' => 'never_local_alone',
            'model_role' => 'quality',
            'purpose' => 'Never let a local model attach a document or relationship to FT by itself.',
            'input_kind' => 'approval_bundle',
            'output_schema' => 'approval_required',
            'chunk_chars' => 5000,
            'target_output_chars' => 800,
            'stages' => ['human_review_required', 'deterministic_apply_only'],
        ],
    ],
];
